name: student_management
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^15.1.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  flutter_svg: ^2.0.17
  flutter_native_splash: ^2.4.6
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/icon/icon.png
    - assets/logo_drawer.svg







flutter_native_splash:

  color: "#ffffff"
  background_image: "assets/logo.png"
  color_dark: "#042a49"
  background_image_dark: "assets/logo.png"
  android_12:
    image: assets/logo.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
  android: true
  color_android: "#ffffff"
  color_dark_android: "#000000"

  image_android: assets/logo.png
  image_dark_android: assets/logo.png
  

flutter_launcher_icons:
  android: "Tuition Tracker" 
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21